export const icons = {
    back: require('../../assets/images/back.png'),
    google: require('../../assets/images/google.png'),
    apple: require('../../assets/images/apple.png'),
    hide: require('../../assets/images/hide.png'),
    show: require('../../assets/images/show.png'),
    next: require('../../assets/images/next.png'),
    user: require('../../assets/images/user.png'),
    hand: require('../../assets/images/hand.png'),
    bell: require('../../assets/images/bell.png'),
    search: require('../../assets/images/search.png'),
    Capture1: require('../../assets/images/Capture1.png'),
    shopee: require('../../assets/images/shopee.png'),
    M: require('../../assets/images/M.png'),
    save: require('../../assets/images/save.png'),
    light: require('../../assets/images/light.png'),
    sell: require('../../assets/images/sell.png'),
    close: require('../../assets/images/close.png'),
    check: require('../../assets/images/check.png'),
    add1: require('../../assets/images/add1.png'),
    salary: require('../../assets/images/salary.png'),
    job: require('../../assets/images/job.png'),
    employes: require('../../assets/images/employes.png'),
    home: require('../../assets/images/home.png'),
    messenger: require('../../assets/images/messenger.png'),
    user1: require('../../assets/images/user1.png'),
    selary: require('../../assets/images/selary.png'),
    chat: require('../../assets/images/chat.png'),
    man: require('../../assets/images/man.png'),
    notification: require('../../assets/images/notification.png'),
    boy: require('../../assets/images/boy.png'),
    send: require('../../assets/images/send.png'),
    saved1: require('../../assets/images/saved1.png'),
    upload: require('../../assets/images/upload.png'),
    successful: require('../../assets/images/successful.png'),
    settings: require('../../assets/images/settings.png'),
    shopee: require('../../assets/images/shopee.png'),
    uparrow: require('../../assets/images/uparrow.png'),
    downarrow: require('../../assets/images/downarrow.png'),
    // sell: require('../../assets/images/sell.png'),
    document: require('../../assets/images/document.png'),
    editer: require('../../assets/images/editer.png'),
    personal: require('../../assets/images/personal.png'),
    expri: require('../../assets/images/expri.png'),
    notifiacation: require('../../assets/images/notifiacation.png'),
    language: require('../../assets/images/language.png'),
    security: require('../../assets/images/security.png'),
    lagel: require('../../assets/images/lagel.png'),
    help: require('../../assets/images/help.png'),
    aboutas: require('../../assets/images/aboutas.png'),
    rightarrowA:require('../../assets/images/rightarrowA.png'),
    usera:require('../../assets/images/usera.png'),
   sure:require('../../assets/images/sure.png'),
   eduction:require('../../assets/images/eduction.png'),
   date:require('../../assets/images/date.png'),
   sar:require('../../assets/images/sar.png'),
Editicon:require('../../assets/images/Editicon.png'),
aboutusss:require('../../assets/images/aboutusss.png'),
helper:require('../../assets/images/helper.png'),
legelllll:require('../../assets/images/legelllll.png'),
Secuu:require('../../assets/images/Secuu.png'),
languageee:require('../../assets/images/languageee.png'),
Noooti:require('../../assets/images/Noooti.png'),
EExxx:require('../../assets/images/EExxx.png'),
userp:require('../../assets/images/userp.png'),
settingarrow:require('../../assets/images/settingarrow.png'),

};
