export const String = {
    thebestapp: 'The best app for Find\nYour Dream Job',
    Semper: 'Semper in cursus magns et eu varius\n nunc adipiscing. Elementum justo,\nlaoreet id sem.',
    betterfuture: 'Better future is starting\n from you',
    application: 'Application surely\n viewed by each\n company',
    Next: 'Next',
    get: 'Get Strated',
    create: 'Create account',
    lorem1: 'Lorem ipsum dolor sit amet',
    google: 'Coutinue with Google',
    apple: 'Coutinue with Apple',
    or: 'Or continue with',
    withemail: 'Continue with Email',
    Already: 'Already have an account ? ',
    Login: 'Login',
    Bysigning: 'By signing up you agree to our ',
    Terms: 'Terms',
    and: 'and',
    conditions: '  Conditions of use',
    youaccount: 'Complete your account',
    select: 'Select a Country',
    choose: 'Choose Job Type',
    areyou: 'Are you looking for a new job or\n looking for new employee',
    find: 'Find a job',
    employee: 'Find a employee',
    jobdream: "It's easy to find your\ndream jobs here with\n us",
    employeedream: "It's easy to find\n enployees here with\nus.",
    continue: 'Continue',
    agree: 'I agree to the',
    termsofservice: 'Terms of Service  ',
    condition: 'Conditions of Use ',
    including: 'including consent',
    toelectronic: 'to electronic communications and I\n affirm that the information provided\n is my own.',
    agrecontinue: ' Agree and Continue',
    Disgree: 'Disgree',
    what: 'What is your\n specialization?',
    lorem: 'Lorem ipsum dolor sit amet, consectetur',
    design: 'Design & Creative',
    development: 'Developmenr & IT',
    engineering: 'Engineering & Architecture',
    salas: 'Sales & Marketing',
    writing: 'Writing',
    finance: 'Finance',
    Selected: 'Selected a Country',
    search: 'Serch...',
    enter: 'Enter OTP',
    wehavejust: 'We have just sent you 4 digit code via your',
    didnot: "Didn't receive code? ",
    resend: 'Resend Code',
    hii: "Hi, Welcome Back! ",
    find: 'Find your dream job',
    recommendation: 'Recommendation',
    recent: 'Recent Jobs',
    findjob: 'Find Jobs',
    applyfilter: 'Apply Filter',
    jobdetails: 'Job Details',
    jobdescription: ' Lorem ipsum dolor sit amet. Consectetur\n adipiscing elit. Nec porttitor magna luctus\n tortor. Pretium malesuada lobortis consequat\n et mauris.',
    loremipsum: 'Lorem ipsum dolor sit amet. Consectetur',
    applynow: 'Apply Now',
    applyed: 'Applied',
    welcomehii: 'Hi, Welcome Back!',
    singup: 'SingUp',
    ChanceSeptimus: 'Chance Septimus',
    save: 'Saved',
    Applyjob: 'Apply job',
    fullname: 'Full Name',
    emailaddress: 'Email Address',
    uploadcv: 'Upload CV',
    uploadFILE: 'Upload File',
    website: 'Website.Blog.or Portfollo',
    success: 'Success',
    youapplication: 'Your Application is succesfully sent',
    notification: 'Notifications',
    Loremipsumdolorsitamet: ' Lorem ipsum dolor sit amet. \n consecteture adipicing elit',
    profile: 'Profile',
    UI: 'UI/UX Designer, Web Design, Mobile App \n Design',
    aboutt: 'Lorem ipsum dolor sit amet, consectetur \nadipicing elit. Libero, cursus modalstie \nnullam ac pharetra est nec enim. Vel \neleifend semper nunc faucibus donec \npretium.',
    settings:'Settings',
    ProfileCo:'Profile Completeness',
    quality:'Quality profiles are 5 time more ',
    qualit:'likely to get hired by clients.',
    account:'Account',
    personal:'Personal Info',
    Ex:'Experience',
    Noti:'Notification',
    lang:'Language',
    sec:'security',
    legal:'Legal and Policies',
    help:'Help & Feedback',
    about:'About Us', 
    genenal:'General',
    about:'About',
    log:'Logout', 
    sure:'Are you sure?',
    ullam:'Ullamcorper imperdiet urna id non\n sed est sem.',
    addnewposition:'Add New Position',
    addneweducation:'Add New Education',
    savech:'Save Changes',
    terms:'Terms',
    termslorem:' Lorem ipsum dolor sit amet. consectetur\n adipiscing elit. Eget. Eget ornare quam velfacilisis\n feugiat amet sagittis srcu, tortor. Sapien,\n consequat ultrices morbi orci semper sit nulla.\n Leo auctor ut etiam eat, amet aliquet ut\n vivamus. Odio vulputate eat id tincidunt\n fames.',
    changes:'Changes to me Service and/or Terms:',
    massages:'Messages Notification',
    newpost:'New Post',
    interview:'Interview Invited',
    mess:'Message',
    newjobpost:'New Post Job', 
    savechange:'Save Changes',
    newchat:'New Chat',
    saved:'Saved',
    jobDescription:'Job Description'

}